--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XeonCh/PlayerWarpsUI
build-by-default: true
branches:
- main
projects:
  PlayerWarpsUI:
    path: ""
    icon: icon.png
    - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
       version: ^3.0.2
...
