name: PlayerWarpsUI
main: XeonCh\PlayerWarpsUI\PlayerWarps
src-namespace-prefix: XeonCh\PlayerWarpsUI
version: 1.0.0
api: 4.0.0
author: 
- XeonCh
- dhnnz
depend: BedrockEconomy

commands:
  pwarp:
    description: "Player warp command"
    permission: playerwarpsui.pwarp.cmd
permissions:
   playerwarpsui.pwarp.cmd:
     default: true
     description: "Main command"
   playerwarpsui.pwarp.create:
     default: op
     description: "Create pwarp"
   playerwarpsui.pwarp.delete:
     default: op
     description: "Delete Pwarp"
   playerwarpsui.pwarp.newpos:
     default: op
     description: "Create new pos pwarp"
   playerwarpsui.pwarp.info:
     default: op
     description: "Show info pwarp"
   playerwarpsui.pwarp.help:
     default: true
     description: "Show help command"