#CONFIG PLAYER WARPS
#DONT CHANGE AUTHOR

#██╗░░██╗███████╗░█████╗░███╗░░██╗
#╚██╗██╔╝██╔════╝██╔══██╗████╗░██║
#░╚███╔╝░█████╗░░██║░░██║██╔██╗██║
#░██╔██╗░██╔══╝░░██║░░██║██║╚████║
#██╔╝╚██╗███████╗╚█████╔╝██║░╚███║
#╚═╝░░╚═╝╚══════╝░╚════╝░╚═╝░░╚══╝
#
#░█████╗░██╗░░██╗
#██╔══██╗██║░░██║
#██║░░╚═╝███████║
#██║░░██╗██╔══██║
#╚█████╔╝██║░░██║
#░╚════╝░╚═╝░░╚═╝

#PREFIX MESSAGE
Prefix: "§7[§ePlayerWarps§7] "

# ECONOMY PROVIDER
# ecomomys,economyapi (EconomyAPI)
# bedrockeconomy (BedrockEconomy)
# xp,exp,experience (Exp)
economy:
  provider: economyapi
  
#NO PERMISSIONS CHAT
no-permission: "§cYou dont have permission to use this command"

#PRICE FOR CREATE & NEWPOS PLAYER WARPS
#ONLY NUMERIC
price:
  create: "100"
  newpos: "100"
  
#MENU CONFIG
menu:
  title: "§ePlayer Warp"
  content: "Player Warp Menu by Xeon"
  
#################################
#  {PLAYER} = Get Name Player
#  {pwarp} = Namme pwarp
#  {owner} = Name Owner Pwarp
#  {x} = Position X Pwarp
#  {y} = Position Y Pwarp
#  {z} = Position z Pwarp
#  {world} = World Pwarp
#  AND USE & FOR COLORONG
#  EXAMPLE
Tp-Message: "&a{PLAYER} Teleported to {pwarp}, Owner {owner}"
